# Generated by Django 2.2.4 on 2019-09-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0002_smsqueue_provider_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsqueue',
            name='provider_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
