# Generated by Django 2.2.4 on 2019-09-24 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0003_auto_20190923_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsqueue',
            name='msg_status',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50, message='The status must not be more than 15 characters long')]),
        ),
    ]
