# Generated by Django 2.2.4 on 2019-09-25 04:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0004_auto_20190924_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsqueue',
            name='message',
            field=models.CharField(max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000, message='The message to be sent must not be more than 1000 characters')]),
        ),
    ]
